/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    App: typeof import('./src/App.vue')['default']
    Child1: typeof import('./src/views/child1/index.vue')['default']
    Child2: typeof import('./src/views/child2/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Page1: typeof import('./src/views/page1/index.vue')['default']
    Page2: typeof import('./src/views/page2/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
